name: CI for-Golang

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.2'

    - name: Check out Code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Build
      run: go build -v ./....
      
    - name: Test
      run: go test -v ./....
