name: Continuous Integration-Golang

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.13'
      id: go

    - name: Check out Code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -v golangci-lint $(go list -f '{{.Dir}}/...' -m | xargs))

    - name: Test
      run: go test -v golangci-lint $(go list -f '{{.Dir}}/...' -m | xargs))

    - name: Finish pipeline
      run:
        echo "Pipeline has finished"  
